# Generated by Django 5.2.5 on 2025-09-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bran_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bran_nm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('bran', models.ForeignKey(db_column='bran_id', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.branch')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pizza_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
