# Generated by Django 5.2.5 on 2025-08-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('pizza_type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pizza_nm', models.CharField(max_length=50)),
                ('pizza_categ', models.CharField(max_length=50)),
                ('pizza_img_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pizza_types',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('pizza_type', models.ForeignKey(db_column='pizza_type_id', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzatype')),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
    ]
