# Generated by Django 5.2.5 on 2025-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('member_pwd', models.CharField(max_length=100)),
                ('member_nm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
