# Generated by Django 5.2.5 on 2025-08-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=50)),
                ('bran_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('pizza', models.ForeignKey(db_column='pizza_id', on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
