# Generated by Django 5.2.5 on 2025-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bran_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bran_nm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
